name: book_list_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  
  
  cupertino_icons: ^1.0.8
  # for making http requests
  http: ^1.3.0
  #helps to implement value based equality
  equatable: ^2.0.7
  # for show and cache the network image
  cached_network_image: ^3.4.1
  #Check the connectivity to the internet
  connectivity_plus: ^6.1.4
  # for state management
  flutter_bloc: ^9.1.0
  # for local database and caching
  hive: ^2.2.3
  # for local database and caching
  hive_flutter: ^1.1.0
  # for getting the path of the app
  path_provider: ^2.1.5
  # for show multi devices
  device_preview: ^1.2.0
  # for the using Google font
  google_fonts: ^6.2.1
  #for dependency injection
  get_it: ^8.0.3
  # for responsive layout
  responsive_builder: ^0.7.1
  # for access ENV file
  envied: ^1.1.1

  #Handle Navigation and routing
  go_router: ^15.1.1
  # for logging
  logger: ^2.5.0
  # Code generation for immutable classes
  freezed: any
  #for freezed annotations
  freezed_annotation: any
  #for using json serializable annotations
  json_annotation: ^4.9.0
  # for skeleton loading
  skeletonizer: any

  #used for add animation to list
  auto_animated: ^3.2.0
  #for handle error on Screens
  empty_widget:
    git:
      url: https://github.com/ElGenius-developer/flutter_empty_widget
#! ###################################################################
#! #########################Dev Dependencies##########################
#! ###################################################################

dev_dependencies:
  flutter_test:
    sdk: flutter
  # for json to dart conversion
  json_serializable: "^6.9.0"
  # for code generation
  build_runner: "^2.4.13"
  # for generate env file properties
  envied_generator: ^1.1.1
  #  for generate TypeAdapters to store any class.
  hive_generator: ^2.0.1
  flutter_lints: ^5.0.0


flutter:
  
  uses-material-design: true

  assets:
    - assets/

  
  
