part of 'app_router.dart';

extension GoRouterExtension on GoRouter {
  GoRouter copyWith({
    List<RouteBase>? routes,
    Codec<Object?, Object?>? extraCodec,
    GoRouterPageBuilder? errorPageBuilder,
    GoRouterWidgetBuilder? errorBuilder,
    GoRouterRedirect? redirect,
    Listenable? refreshListenable,
    int? redirectLimit,
    GoExceptionHandler? onException,
    bool? routerNeglect,
    String? initialLocation,
    bool overridePlatformDefaultLocation = false,
    Object? initialExtra,
    List<NavigatorObserver>? observers,
    bool debugLogDiagnostics = false,
    GlobalKey<NavigatorState>? navigatorKey,
    String? restorationScopeId,
    bool requestFocus = true,
  }) => GoRouter(
    routes: routes ?? configuration.routes,
    extraCodec: extraCodec ?? configuration.extraCodec,
    errorBuilder: errorBuilder ?? (_, state) => const Scaffold(body: Center(child: Text('Error, No Page Found'))),
    routerNeglect: routerNeglect ?? routerDelegate.routerNeglect,
    initialLocation: initialLocation,
    overridePlatformDefaultLocation: overridePlatformDefaultLocation,
    initialExtra: initialExtra,
    observers: observers,
    debugLogDiagnostics: debugLogDiagnostics,
    navigatorKey: navigatorKey ?? configuration.navigatorKey,
    restorationScopeId: restorationScopeId,
    requestFocus: requestFocus,
    onException: onException,
    redirect: redirect,
    refreshListenable: refreshListenable,
    redirectLimit: redirectLimit ?? configuration.redirectLimit,
    errorPageBuilder: errorPageBuilder,
  );
}
